# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - privatefe

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          $env:CI="false"
          npm install
          npm run build
          
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.5
        with:
          filename: release.zip
          path: ./build/*
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'publicfe'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FE85D67FD83A44118BB81EF143F2FCD8 }}
          package: release.zip
